#ifndef USDTWEAK_API_H
#define USDTWEAK_API_H

#include <pxr/base/arch/export.h>

#if defined(USDTWEAK_STATIC)
#define USDTWEAK_API
#define USDTWEAK_API_TEMPLATE_CLASS(...)
#define USDTWEAK_API_TEMPLATE_STRUCT(...)
#define USDTWEAK_LOCAL
#else
#if defined(USDTWEAK_EXPORTS)
#define USDTWEAK_API ARCH_EXPORT
#define USDTWEAK_API_TEMPLATE_CLASS(...) ARCH_EXPORT_TEMPLATE(class, __VA_ARGS__)
#define USDTWEAK_API_TEMPLATE_STRUCT(...) ARCH_EXPORT_TEMPLATE(struct, __VA_ARGS__)
#else
#define USDTWEAK_API ARCH_IMPORT
#define USDTWEAK_API_TEMPLATE_CLASS(...) ARCH_IMPORT_TEMPLATE(class, __VA_ARGS__)
#define USDTWEAK_API_TEMPLATE_STRUCT(...) ARCH_IMPORT_TEMPLATE(struct, __VA_ARGS__)
#endif
#define USDTWEAK_LOCAL ARCH_HIDDEN
#endif

#endif